Md 88 implements category crud
trukaSoftware/menu-digital pull request #92
Opened 2023-07-18 14:17 UTC by claudiocassimiro

2023-07-18 18:36 UTC, ebertonArouxa requested changes

2023-07-18 18:36 UTC, ebertonArouxa commented on src/app/api/services/category/createCategoryService.ts
> +    return categoy;
```suggestion
    const category = await prisma.productCategories.create({
      data: {
        companyId,
        name,
      },
    });

    return category;
```

2023-07-18 18:36 UTC, ebertonArouxa commented on src/app/api/services/category/editCategoryService.ts
> +        `${name} já é o nome de uma categória existente, escolha outro nome`
```suggestion
        `${name} já é o nome de uma categoria existente, escolha outro nome`
```

2023-07-18 19:42 UTC, claudiocassimiro commented on src/app/api/services/category/editCategoryService.ts
> +        `${name} já é o nome de uma categória existente, escolha outro nome`
Categoria com ó é Fodaa ksksksks

2023-07-19 00:08 UTC, EricksonSiqueira approved these changes

2023-07-19 00:12 UTC, ebertonArouxa approved these changes

2023-07-19 00:12 UTC, merged